"""
Variant plugin contracts for multi-instance UI + agent behavior.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol

from interview_agent.models import AnalysisItem, TranscriptEvent


@dataclass(frozen=True)
class ChecklistItem:
    """Checklist definition used by variant-specific UIs."""

    id: str
    label: str
    keywords: tuple[str, ...]


@dataclass(frozen=True)
class VariantUiConfig:
    """UI defaults and content for a variant."""

    page_title: str
    page_icon: str
    header_title: str
    candidate_name: str
    meeting_url: str
    interview_script: tuple[tuple[str, str], ...]
    checklist_items: tuple[ChecklistItem, ...]


class VariantPlugin(Protocol):
    """Interface for variant-specific agent + UI behavior."""

    variant_id: str
    display_name: str
    ui: VariantUiConfig

    async def on_session_start(self, session_context: dict[str, Any]) -> None:
        """Lifecycle hook when a session starts."""

    async def on_transcript(
        self,
        event: TranscriptEvent,
        session_context: dict[str, Any],
    ) -> None:
        """Lifecycle hook for each transcript event."""

    async def on_session_end(self, session_summary: dict[str, Any]) -> None:
        """Lifecycle hook when a session ends."""

    def build_analysis_context(
        self,
        base_context: dict[str, Any],
        event: TranscriptEvent,
    ) -> dict[str, Any]:
        """Inject variant-specific context before agent analysis."""

    def transform_analysis_item(self, analysis_item: AnalysisItem) -> AnalysisItem:
        """Post-process analysis item generated by shared ingest pipeline."""


class BaseVariantPlugin:
    """No-op baseline plugin."""

    variant_id = "base"
    display_name = "Base"
    ui: VariantUiConfig

    async def on_session_start(self, session_context: dict[str, Any]) -> None:
        return

    async def on_transcript(
        self,
        event: TranscriptEvent,
        session_context: dict[str, Any],
    ) -> None:
        return

    async def on_session_end(self, session_summary: dict[str, Any]) -> None:
        return

    def build_analysis_context(
        self,
        base_context: dict[str, Any],
        event: TranscriptEvent,
    ) -> dict[str, Any]:
        return base_context

    def transform_analysis_item(self, analysis_item: AnalysisItem) -> AnalysisItem:
        return analysis_item
